In [46]:
import pandas as pd
import numpy as np
from herramientas import obtener_resumen_valores_unicos

In [47]:
df = pd.read_csv('data/train.csv')

In [48]:
df.head()

id surgery    age  hospital_number  rectal_temp  pulse  respiratory_rate  \
0   0     yes  adult           530001         38.1  132.0              24.0   
1   1     yes  adult           533836         37.5   88.0              12.0   
2   2     yes  adult           529812         38.3  120.0              28.0   
3   3     yes  adult          5262541         37.1   72.0              30.0   
4   4      no  adult          5299629         38.0   52.0              48.0   

  temp_of_extremities peripheral_pulse mucous_membrane  ...  \
0                cool          reduced   dark_cyanotic  ...   
1                cool           normal   pale_cyanotic  ...   
2                cool          reduced       pale_pink  ...   
3                cold          reduced       pale_pink  ...   
4              normal           normal     normal_pink  ...   

  packed_cell_volume total_protein abdomo_appearance abdomo_protein  \
0               57.0           8.5     serosanguious            3.4   
1               33.0          64.0     serosanguious            2.0   
2               37.0           6.4     serosanguious            3.4   
3               53.0           7.0            cloudy            3.9   
4               47.0           7.3            cloudy            2.6   

  surgical_lesion lesion_1  lesion_2 lesion_3 cp_data     outcome  
0             yes     2209         0        0      no        died  
1             yes     2208         0        0      no  euthanized  
2             yes     5124         0        0      no       lived  
3             yes     2208         0        0     yes       lived  
4              no        0         0        0     yes       lived  

[5 rows x 29 columns]

In [49]:
obtener_resumen_valores_unicos(df)

Columna Tipo de Dato  Valores Únicos  Total Valores  \
0                      id        int64            1235           1235   
1                 surgery       object               2           1235   
2                     age       object               2           1235   
3         hospital_number        int64             255           1235   
4             rectal_temp      float64              43           1235   
5                   pulse      float64              50           1235   
6        respiratory_rate      float64              37           1235   
7     temp_of_extremities       object               4           1196   
8        peripheral_pulse       object               4           1175   
9         mucous_membrane       object               6           1214   
10  capillary_refill_time       object               3           1229   
11                   pain       object               6           1191   
12            peristalsis       object               5           1215   
13   abdominal_distention       object               4           1212   
14       nasogastric_tube       object               3           1155   
15     nasogastric_reflux       object               4           1214   
16  nasogastric_reflux_ph      float64              26           1235   
17      rectal_exam_feces       object               5           1045   
18                abdomen       object               5           1022   
19     packed_cell_volume      float64              49           1235   
20          total_protein      float64              83           1235   
21      abdomo_appearance       object               3           1187   
22         abdomo_protein      float64              54           1235   
23        surgical_lesion       object               2           1235   
24               lesion_1        int64              57           1235   
25               lesion_2        int64               4           1235   
26               lesion_3        int64               2           1235   
27                cp_data       object               2           1235   
28                outcome       object               3           1235   

    Valores Nulos  
0               0  
1               0  
2               0  
3               0  
4               0  
5               0  
6               0  
7              39  
8              60  
9              21  
10              6  
11             44  
12             20  
13             23  
14             80  
15             21  
16              0  
17            190  
18            213  
19              0  
20              0  
21             48  
22              0  
23              0  
24              0  
25              0  
26              0  
27              0  
28              0

In [50]:
# Eliminar filas con valores nulos
df = df.dropna()

In [51]:
df = df.drop('id', axis=1)

In [52]:
obtener_resumen_valores_unicos(df)

Columna Tipo de Dato  Valores Únicos  Total Valores  \
0                 surgery       object               2            771   
1                     age       object               2            771   
2         hospital_number        int64             213            771   
3             rectal_temp      float64              39            771   
4                   pulse      float64              49            771   
5        respiratory_rate      float64              34            771   
6     temp_of_extremities       object               4            771   
7        peripheral_pulse       object               4            771   
8         mucous_membrane       object               6            771   
9   capillary_refill_time       object               3            771   
10                   pain       object               5            771   
11            peristalsis       object               4            771   
12   abdominal_distention       object               4            771   
13       nasogastric_tube       object               3            771   
14     nasogastric_reflux       object               4            771   
15  nasogastric_reflux_ph      float64              23            771   
16      rectal_exam_feces       object               5            771   
17                abdomen       object               5            771   
18     packed_cell_volume      float64              48            771   
19          total_protein      float64              80            771   
20      abdomo_appearance       object               3            771   
21         abdomo_protein      float64              51            771   
22        surgical_lesion       object               2            771   
23               lesion_1        int64              51            771   
24               lesion_2        int64               3            771   
25               lesion_3        int64               2            771   
26                cp_data       object               2            771   
27                outcome       object               3            771   

    Valores Nulos  
0               0  
1               0  
2               0  
3               0  
4               0  
5               0  
6               0  
7               0  
8               0  
9               0  
10              0  
11              0  
12              0  
13              0  
14              0  
15              0  
16              0  
17              0  
18              0  
19              0  
20              0  
21              0  
22              0  
23              0  
24              0  
25              0  
26              0  
27              0

In [53]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['outcome'] = label_encoder.fit_transform(df['outcome'])


In [54]:
# Lista de nombres de las variables categóricas que deseas codificar
variables_categoricas = ['surgery', 'age', 'temp_of_extremities', 'peripheral_pulse', 'mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis', 'abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux', 'rectal_exam_feces', 'abdomen', 'abdomo_appearance', 'surgical_lesion', 'cp_data']

# Aplicar one-hot encoding a todas las variables categóricas en la lista
df_encoded = pd.get_dummies(df, columns=variables_categoricas, drop_first=True)


In [58]:
from sklearn.model_selection import train_test_split

X = df_encoded.drop('outcome', axis=1)
y = df_encoded['outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15)


# modelo Random Forest Classifier

In [59]:
# Importa el modelo Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

# Crea una instancia del modelo
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Paso 5: Entrenamiento del modelo
model.fit(X_train, y_train)

# Paso 6: Evaluación del modelo
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(classification_rep)

# Paso 7: Ajuste final del modelo (si es necesario)

# Paso 8: Predicciones en nuevos datos
# Puedes usar model.predict() para hacer predicciones en nuevos datos

Accuracy: 0.7032258064516129
Confusion Matrix:
[[49  1 21]
 [ 5  7  7]
 [10  2 53]]
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.69      0.73        71
           1       0.70      0.37      0.48        19
           2       0.65      0.82      0.73        65

    accuracy                           0.70       155
   macro avg       0.71      0.62      0.64       155
weighted avg       0.71      0.70      0.70       155

